//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.03 at 08:04:31 PM CEST 
//


package org.openestate.is24.restapi.xml.realestates;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.openestate.is24.restapi.xml.common.Paging;
import org.openestate.is24.restapi.xml.offerlistelement.RealEstateList;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Paging" type="{http://rest.immobilienscout24.de/schema/common/1.0}Paging"/>
 *         &lt;element name="realEstateList" type="{http://rest.immobilienscout24.de/schema/offer/listelement/1.0}realEstateList"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "paging",
    "realEstateList"
})
@XmlRootElement(name = "realEstates")
public class RealEstates {

    @XmlElement(name = "Paging", required = true)
    protected Paging paging;
    @XmlElement(required = true)
    protected RealEstateList realEstateList;

    /**
     * Gets the value of the paging property.
     * 
     * @return
     *     possible object is
     *     {@link Paging }
     *     
     */
    public Paging getPaging() {
        return paging;
    }

    /**
     * Sets the value of the paging property.
     * 
     * @param value
     *     allowed object is
     *     {@link Paging }
     *     
     */
    public void setPaging(Paging value) {
        this.paging = value;
    }

    /**
     * Gets the value of the realEstateList property.
     * 
     * @return
     *     possible object is
     *     {@link RealEstateList }
     *     
     */
    public RealEstateList getRealEstateList() {
        return realEstateList;
    }

    /**
     * Sets the value of the realEstateList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RealEstateList }
     *     
     */
    public void setRealEstateList(RealEstateList value) {
        this.realEstateList = value;
    }

}
