//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.14 at 12:30:43 AM CET 
//


package org.openestate.is24.restapi.xml.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ShortTermAccommodationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ShortTermAccommodationType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="APARTMENT"/>
 *     &lt;enumeration value="FLAT"/>
 *     &lt;enumeration value="HOUSE"/>
 *     &lt;enumeration value="ROOM"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ShortTermAccommodationType")
@XmlEnum
public enum ShortTermAccommodationType {


    /**
     * Wohnung und Apartment
     * 
     */
    APARTMENT,

    /**
     * Wohnung
     * 
     */
    FLAT,

    /**
     * Haus
     * 
     */
    HOUSE,

    /**
     * Zimmer
     * 
     */
    ROOM;

    public String value() {
        return name();
    }

    public static ShortTermAccommodationType fromValue(String v) {
        return valueOf(v);
    }

}
